### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'fxmarketapi'

### ISSUE THREAD

**Issue by ekkesa** [rob196/home-assistant-fxmarketapi#7]
Error showing up on Home Assistant indicating that this will not be supported in 2021.6 on due to lack of version key

"No 'version' key in the manifest file for custom integration 'fxmarketapi'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'fxmarketapi"

**Comment by rob196** [comment]
Thanks for raising this

Fixed in Release 1.0.3

**Comment by ekkesa** [comment]
Updated! Thank you...
